spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: q1w2e3r4
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9090

jwt:
  token:
    secret: b4d09a477bda03b3b44e8f6f552284c6acf1142bfcdc7e0b07e4d21f1efda4e7
    expiration: 3600000

logging:
  level:
    org:
      springframework:
        aop: DEBUG
    in:
      ynt:
        shop:
          app: DEBUG